<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <actionOverrides>
        <actionName>View</actionName>
        <content>AdvisingAlert</content>
        <formFactor>Large</formFactor>
        <skipRecordTypeSelect>false</skipRecordTypeSelect>
        <type>Flexipage</type>
        <pageOrSobjectType>sfal__Alert__c</pageOrSobjectType>
    </actionOverrides>
    <actionOverrides>
        <actionName>View</actionName>
        <content>SuccessPlan</content>
        <formFactor>Large</formFactor>
        <skipRecordTypeSelect>false</skipRecordTypeSelect>
        <type>Flexipage</type>
        <pageOrSobjectType>sfal__SuccessPlan__c</pageOrSobjectType>
    </actionOverrides>
    <brand>
        <headerColor>#0070D2</headerColor>
        <shouldOverrideOrgTheme>false</shouldOverrideOrgTheme>
    </brand>
    <description>Salesforce.org Advisor Link</description>
    <formFactors>Large</formFactors>
    <isNavAutoTempTabsDisabled>false</isNavAutoTempTabsDisabled>
    <isNavPersonalizationDisabled>false</isNavPersonalizationDisabled>
    <label>Advisor Link</label>
    <navType>Console</navType>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>User_Record_Page1</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>User</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>SAL Advisor</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>User_Record_Page1</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>User</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Admin</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>AdvisingEvent</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Event</pageOrSobjectType>
        <recordType>Event.AdvisingEvent</recordType>
        <type>Flexipage</type>
        <profile>SAL Advisor</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>AdviseeRecord</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Case</pageOrSobjectType>
        <recordType>Case.AdviseeRecord</recordType>
        <type>Flexipage</type>
        <profile>Admin</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>AdvisingEvent</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Event</pageOrSobjectType>
        <recordType>Event.AdvisingEvent</recordType>
        <type>Flexipage</type>
        <profile>Admin</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>AdviseeRecord</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Case</pageOrSobjectType>
        <recordType>Case.AdviseeRecord</recordType>
        <type>Flexipage</type>
        <profile>SAL Advisor</profile>
    </profileActionOverrides>
    <tabs>standard-home</tabs>
    <tabs>standard-Contact</tabs>
    <tabs>standard-Event</tabs>
    <tabs>standard-ContentNote</tabs>
    <tabs>standard-Case</tabs>
    <tabs>sfal__Alert__c</tabs>
    <tabs>sfal__SuccessPlan__c</tabs>
    <tabs>standard-report</tabs>
    <tabs>standard-Dashboard</tabs>
    <tabs>Bulk_Alerts</tabs>
    <uiType>Lightning</uiType>
    <utilityBar>Advisor_Link_UtilityBar</utilityBar>
    <workspaceConfig>
        <mappings>
            <tab>Bulk_Alerts</tab>
        </mappings>
        <mappings>
            <fieldName>sfal__AdviseeRecord__c</fieldName>
            <tab>sfal__Alert__c</tab>
        </mappings>
        <mappings>
            <fieldName>sfal__AdviseeRecord__c</fieldName>
            <tab>sfal__SuccessPlan__c</tab>
        </mappings>
        <mappings>
            <fieldName>ContactId</fieldName>
            <tab>standard-Case</tab>
        </mappings>
        <mappings>
            <tab>standard-Contact</tab>
        </mappings>
        <mappings>
            <tab>standard-ContentNote</tab>
        </mappings>
        <mappings>
            <tab>standard-Dashboard</tab>
        </mappings>
        <mappings>
            <tab>standard-Event</tab>
        </mappings>
        <mappings>
            <tab>standard-home</tab>
        </mappings>
        <mappings>
            <tab>standard-report</tab>
        </mappings>
    </workspaceConfig>
</CustomApplication>
